# Generated by Django 2.2 on 2021-01-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='desc',
            field=models.TextField(default='none'),
        ),
    ]
